/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GatewayContractsAssessmentAddQuestionRequest,
  GatewayContractsAssessmentCourseQuizStatusRequest,
  GatewayContractsAssessmentCreateQuiz,
  GatewayContractsAssessmentGetQuizForModuleRequest,
  GatewayContractsAssessmentGetUnquizzedRequest,
  GatewayContractsAssessmentResultRequest,
  GatewayContractsAssessmentSubmitQuiz
} from '../models';




interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class AssessmentGatewayService {
  private readonly http = inject(HttpClient);
 postApiAssessmentQuizModule<TData = void>(gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuizModule<TData = void>(gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuizModule<TData = void>(gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuizModule<TData = void>(
    gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz/module`,
      gatewayContractsAssessmentGetQuizForModuleRequest,options
    );
  }
 postApiAssessmentQuiz<TData = void>(gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuiz<TData = void>(gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuiz<TData = void>(gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuiz<TData = void>(
    gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz`,
      gatewayContractsAssessmentCreateQuiz,options
    );
  }
 postApiAssessmentQuizQuestions<TData = void>(gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuizQuestions<TData = void>(gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuizQuestions<TData = void>(gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuizQuestions<TData = void>(
    gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz/questions`,
      gatewayContractsAssessmentAddQuestionRequest,options
    );
  }
 postApiAssessmentQuizSubmit<TData = void>(gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuizSubmit<TData = void>(gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuizSubmit<TData = void>(gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuizSubmit<TData = void>(
    gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz/submit`,
      gatewayContractsAssessmentSubmitQuiz,options
    );
  }
 postApiAssessmentQuizResult<TData = void>(gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuizResult<TData = void>(gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuizResult<TData = void>(gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuizResult<TData = void>(
    gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz/result`,
      gatewayContractsAssessmentResultRequest,options
    );
  }
 postApiAssessmentCourseQuizStatus<TData = void>(gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentCourseQuizStatus<TData = void>(gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentCourseQuizStatus<TData = void>(gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentCourseQuizStatus<TData = void>(
    gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/course/quiz-status`,
      gatewayContractsAssessmentCourseQuizStatusRequest,options
    );
  }
 postApiAssessmentCourseUnquizzedModules<TData = void>(gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentCourseUnquizzedModules<TData = void>(gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentCourseUnquizzedModules<TData = void>(gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentCourseUnquizzedModules<TData = void>(
    gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/course/unquizzed-modules`,
      gatewayContractsAssessmentGetUnquizzedRequest,options
    );
  }
};

export type PostApiAssessmentQuizModuleClientResult = NonNullable<void>
export type PostApiAssessmentQuizClientResult = NonNullable<void>
export type PostApiAssessmentQuizQuestionsClientResult = NonNullable<void>
export type PostApiAssessmentQuizSubmitClientResult = NonNullable<void>
export type PostApiAssessmentQuizResultClientResult = NonNullable<void>
export type PostApiAssessmentCourseQuizStatusClientResult = NonNullable<void>
export type PostApiAssessmentCourseUnquizzedModulesClientResult = NonNullable<void>
