/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GatewayContractsCourseContinueCourseRequest,
  GatewayContractsCourseCourse,
  GatewayContractsCourseCourseIdRequest,
  GatewayContractsCourseEnrollRequest,
  GatewayContractsCourseModuleIdRequest,
  GatewayContractsCourseUpdateCourseRequest
} from '../models';




interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class GatewayCourseService {
  private readonly http = inject(HttpClient);
 postApiCourseAll<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseAll<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseAll<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseAll<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/all`,undefined,options
    );
  }
 postApiCourseById<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseById<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseById<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseById<TData = void>(
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/by-id`,
      gatewayContractsCourseCourseIdRequest,options
    );
  }
 postApiCourseCreate<TData = void>(gatewayContractsCourseCourse: GatewayContractsCourseCourse, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseCreate<TData = void>(gatewayContractsCourseCourse: GatewayContractsCourseCourse, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseCreate<TData = void>(gatewayContractsCourseCourse: GatewayContractsCourseCourse, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseCreate<TData = void>(
    gatewayContractsCourseCourse: GatewayContractsCourseCourse, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/create`,
      gatewayContractsCourseCourse,options
    );
  }
 postApiCourseUpdate<TData = void>(gatewayContractsCourseUpdateCourseRequest: GatewayContractsCourseUpdateCourseRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseUpdate<TData = void>(gatewayContractsCourseUpdateCourseRequest: GatewayContractsCourseUpdateCourseRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseUpdate<TData = void>(gatewayContractsCourseUpdateCourseRequest: GatewayContractsCourseUpdateCourseRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseUpdate<TData = void>(
    gatewayContractsCourseUpdateCourseRequest: GatewayContractsCourseUpdateCourseRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/update`,
      gatewayContractsCourseUpdateCourseRequest,options
    );
  }
 postApiCourseDelete<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseDelete<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseDelete<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseDelete<TData = void>(
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/delete`,
      gatewayContractsCourseCourseIdRequest,options
    );
  }
 postApiCourseInstructor<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseInstructor<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseInstructor<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseInstructor<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/instructor`,undefined,options
    );
  }
 postApiCourseUnfinished<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseUnfinished<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseUnfinished<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseUnfinished<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/unfinished`,undefined,options
    );
  }
 postApiCourseContinue<TData = void>(gatewayContractsCourseContinueCourseRequest: GatewayContractsCourseContinueCourseRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseContinue<TData = void>(gatewayContractsCourseContinueCourseRequest: GatewayContractsCourseContinueCourseRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseContinue<TData = void>(gatewayContractsCourseContinueCourseRequest: GatewayContractsCourseContinueCourseRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseContinue<TData = void>(
    gatewayContractsCourseContinueCourseRequest: GatewayContractsCourseContinueCourseRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/continue`,
      gatewayContractsCourseContinueCourseRequest,options
    );
  }
 postApiCourseEnroll<TData = void>(gatewayContractsCourseEnrollRequest: GatewayContractsCourseEnrollRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseEnroll<TData = void>(gatewayContractsCourseEnrollRequest: GatewayContractsCourseEnrollRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseEnroll<TData = void>(gatewayContractsCourseEnrollRequest: GatewayContractsCourseEnrollRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseEnroll<TData = void>(
    gatewayContractsCourseEnrollRequest: GatewayContractsCourseEnrollRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/enroll`,
      gatewayContractsCourseEnrollRequest,options
    );
  }
 postApiCourseEnrolled<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseEnrolled<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseEnrolled<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseEnrolled<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/enrolled`,undefined,options
    );
  }
 postApiCourseModules<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseModules<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseModules<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseModules<TData = void>(
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/modules`,
      gatewayContractsCourseCourseIdRequest,options
    );
  }
 postApiCourseModule<TData = void>(gatewayContractsCourseModuleIdRequest: GatewayContractsCourseModuleIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseModule<TData = void>(gatewayContractsCourseModuleIdRequest: GatewayContractsCourseModuleIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseModule<TData = void>(gatewayContractsCourseModuleIdRequest: GatewayContractsCourseModuleIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseModule<TData = void>(
    gatewayContractsCourseModuleIdRequest: GatewayContractsCourseModuleIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/module`,
      gatewayContractsCourseModuleIdRequest,options
    );
  }
 postApiCourseCategories<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseCategories<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseCategories<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseCategories<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/categories`,undefined,options
    );
  }
 postApiCoursePublish<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCoursePublish<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCoursePublish<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCoursePublish<TData = void>(
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/publish`,
      gatewayContractsCourseCourseIdRequest,options
    );
  }
 postApiCourseRestore<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiCourseRestore<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiCourseRestore<TData = void>(gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiCourseRestore<TData = void>(
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/course/restore`,
      gatewayContractsCourseCourseIdRequest,options
    );
  }
};

export type PostApiCourseAllClientResult = NonNullable<void>
export type PostApiCourseByIdClientResult = NonNullable<void>
export type PostApiCourseCreateClientResult = NonNullable<void>
export type PostApiCourseUpdateClientResult = NonNullable<void>
export type PostApiCourseDeleteClientResult = NonNullable<void>
export type PostApiCourseInstructorClientResult = NonNullable<void>
export type PostApiCourseUnfinishedClientResult = NonNullable<void>
export type PostApiCourseContinueClientResult = NonNullable<void>
export type PostApiCourseEnrollClientResult = NonNullable<void>
export type PostApiCourseEnrolledClientResult = NonNullable<void>
export type PostApiCourseModulesClientResult = NonNullable<void>
export type PostApiCourseModuleClientResult = NonNullable<void>
export type PostApiCourseCategoriesClientResult = NonNullable<void>
export type PostApiCoursePublishClientResult = NonNullable<void>
export type PostApiCourseRestoreClientResult = NonNullable<void>
