/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GatewayContractsUsersCompleteProfileRequest,
  GatewayContractsUsersUpdateUserRoleRequest,
  GatewayContractsUsersUserIdRequest
} from '../models';




interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class GatewayUsersService {
  private readonly http = inject(HttpClient);
 postApiUsersAll<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiUsersAll<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiUsersAll<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiUsersAll<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/users/all`,undefined,options
    );
  }
 postApiUsersById<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiUsersById<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiUsersById<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiUsersById<TData = void>(
    gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/users/by-id`,
      gatewayContractsUsersUserIdRequest,options
    );
  }
 postApiUsersDelete<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiUsersDelete<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiUsersDelete<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiUsersDelete<TData = void>(
    gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/users/delete`,
      gatewayContractsUsersUserIdRequest,options
    );
  }
 postApiUsersCompleteProfile<TData = void>(gatewayContractsUsersCompleteProfileRequest: GatewayContractsUsersCompleteProfileRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiUsersCompleteProfile<TData = void>(gatewayContractsUsersCompleteProfileRequest: GatewayContractsUsersCompleteProfileRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiUsersCompleteProfile<TData = void>(gatewayContractsUsersCompleteProfileRequest: GatewayContractsUsersCompleteProfileRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiUsersCompleteProfile<TData = void>(
    gatewayContractsUsersCompleteProfileRequest: GatewayContractsUsersCompleteProfileRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/users/complete-profile`,
      gatewayContractsUsersCompleteProfileRequest,options
    );
  }
 postApiUsersRolesAll<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiUsersRolesAll<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiUsersRolesAll<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiUsersRolesAll<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/users/roles/all`,undefined,options
    );
  }
 postApiUsersRolesUser<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiUsersRolesUser<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiUsersRolesUser<TData = void>(gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiUsersRolesUser<TData = void>(
    gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/users/roles/user`,
      gatewayContractsUsersUserIdRequest,options
    );
  }
 postApiUsersRolesUpdate<TData = void>(gatewayContractsUsersUpdateUserRoleRequest: GatewayContractsUsersUpdateUserRoleRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiUsersRolesUpdate<TData = void>(gatewayContractsUsersUpdateUserRoleRequest: GatewayContractsUsersUpdateUserRoleRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiUsersRolesUpdate<TData = void>(gatewayContractsUsersUpdateUserRoleRequest: GatewayContractsUsersUpdateUserRoleRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiUsersRolesUpdate<TData = void>(
    gatewayContractsUsersUpdateUserRoleRequest: GatewayContractsUsersUpdateUserRoleRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/users/roles/update`,
      gatewayContractsUsersUpdateUserRoleRequest,options
    );
  }
};

export type PostApiUsersAllClientResult = NonNullable<void>
export type PostApiUsersByIdClientResult = NonNullable<void>
export type PostApiUsersDeleteClientResult = NonNullable<void>
export type PostApiUsersCompleteProfileClientResult = NonNullable<void>
export type PostApiUsersRolesAllClientResult = NonNullable<void>
export type PostApiUsersRolesUserClientResult = NonNullable<void>
export type PostApiUsersRolesUpdateClientResult = NonNullable<void>
