/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import {
  Observable
} from 'rxjs';

import type {
  GatewayContractsAuthLoginRequest,
  GatewayContractsAuthRegisterRequest,
  GetApiGatewayAuthExternalResponseParams,
  GetApiGatewayAuthGoogleLoginParams,
  GetApiGatewayAuthLogoutParams,
  GetApiGatewayAuthMicrosoftLoginParams
} from '../models';




interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class GatewayAuthService {
  private readonly http = inject(HttpClient);
 getApiGatewayAuthGoogleLogin<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthGoogleLoginParams>, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiGatewayAuthGoogleLogin<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthGoogleLoginParams>, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiGatewayAuthGoogleLogin<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthGoogleLoginParams>, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiGatewayAuthGoogleLogin<TData = void>(
    params?: DeepNonNullable<GetApiGatewayAuthGoogleLoginParams>, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/GatewayAuth/google-login`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
 getApiGatewayAuthMicrosoftLogin<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthMicrosoftLoginParams>, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiGatewayAuthMicrosoftLogin<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthMicrosoftLoginParams>, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiGatewayAuthMicrosoftLogin<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthMicrosoftLoginParams>, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiGatewayAuthMicrosoftLogin<TData = void>(
    params?: DeepNonNullable<GetApiGatewayAuthMicrosoftLoginParams>, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/GatewayAuth/microsoft-login`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
 getApiGatewayAuthExternalResponse<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthExternalResponseParams>, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiGatewayAuthExternalResponse<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthExternalResponseParams>, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiGatewayAuthExternalResponse<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthExternalResponseParams>, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiGatewayAuthExternalResponse<TData = void>(
    params?: DeepNonNullable<GetApiGatewayAuthExternalResponseParams>, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/GatewayAuth/external-response`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
 postApiGatewayAuthRefresh<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiGatewayAuthRefresh<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiGatewayAuthRefresh<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiGatewayAuthRefresh<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/GatewayAuth/refresh`,undefined,options
    );
  }
 getApiGatewayAuthLogout<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthLogoutParams>, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiGatewayAuthLogout<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthLogoutParams>, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiGatewayAuthLogout<TData = void>(params?: DeepNonNullable<GetApiGatewayAuthLogoutParams>, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiGatewayAuthLogout<TData = void>(
    params?: DeepNonNullable<GetApiGatewayAuthLogoutParams>, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/GatewayAuth/logout`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
 getApiGatewayAuthMe<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiGatewayAuthMe<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiGatewayAuthMe<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiGatewayAuthMe<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/GatewayAuth/me`,options
    );
  }
 postApiGatewayAuthLocalRegister<TData = void>(gatewayContractsAuthRegisterRequest: GatewayContractsAuthRegisterRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiGatewayAuthLocalRegister<TData = void>(gatewayContractsAuthRegisterRequest: GatewayContractsAuthRegisterRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiGatewayAuthLocalRegister<TData = void>(gatewayContractsAuthRegisterRequest: GatewayContractsAuthRegisterRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiGatewayAuthLocalRegister<TData = void>(
    gatewayContractsAuthRegisterRequest: GatewayContractsAuthRegisterRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/GatewayAuth/local-register`,
      gatewayContractsAuthRegisterRequest,options
    );
  }
 postApiGatewayAuthLocalLogin<TData = void>(gatewayContractsAuthLoginRequest: GatewayContractsAuthLoginRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiGatewayAuthLocalLogin<TData = void>(gatewayContractsAuthLoginRequest: GatewayContractsAuthLoginRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiGatewayAuthLocalLogin<TData = void>(gatewayContractsAuthLoginRequest: GatewayContractsAuthLoginRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiGatewayAuthLocalLogin<TData = void>(
    gatewayContractsAuthLoginRequest: GatewayContractsAuthLoginRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/GatewayAuth/local-login`,
      gatewayContractsAuthLoginRequest,options
    );
  }
};

export type GetApiGatewayAuthGoogleLoginClientResult = NonNullable<void>
export type GetApiGatewayAuthMicrosoftLoginClientResult = NonNullable<void>
export type GetApiGatewayAuthExternalResponseClientResult = NonNullable<void>
export type PostApiGatewayAuthRefreshClientResult = NonNullable<void>
export type GetApiGatewayAuthLogoutClientResult = NonNullable<void>
export type GetApiGatewayAuthMeClientResult = NonNullable<void>
export type PostApiGatewayAuthLocalRegisterClientResult = NonNullable<void>
export type PostApiGatewayAuthLocalLoginClientResult = NonNullable<void>
