/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GatewayContractsNotificationEmailRequest,
  GatewayContractsNotificationTemplateRequest,
  GatewayContractsNotificationTriggerNotification,
  GatewayContractsNotificationUserIdRequest
} from '../models';




interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class NotificationGatewayService {
  private readonly http = inject(HttpClient);
 postApiNotificationSend<TData = void>(gatewayContractsNotificationEmailRequest: GatewayContractsNotificationEmailRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiNotificationSend<TData = void>(gatewayContractsNotificationEmailRequest: GatewayContractsNotificationEmailRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiNotificationSend<TData = void>(gatewayContractsNotificationEmailRequest: GatewayContractsNotificationEmailRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiNotificationSend<TData = void>(
    gatewayContractsNotificationEmailRequest: GatewayContractsNotificationEmailRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/notification/send`,
      gatewayContractsNotificationEmailRequest,options
    );
  }
 postApiNotificationTemplateSend<TData = void>(gatewayContractsNotificationTemplateRequest: GatewayContractsNotificationTemplateRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiNotificationTemplateSend<TData = void>(gatewayContractsNotificationTemplateRequest: GatewayContractsNotificationTemplateRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiNotificationTemplateSend<TData = void>(gatewayContractsNotificationTemplateRequest: GatewayContractsNotificationTemplateRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiNotificationTemplateSend<TData = void>(
    gatewayContractsNotificationTemplateRequest: GatewayContractsNotificationTemplateRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/notification/template/send`,
      gatewayContractsNotificationTemplateRequest,options
    );
  }
 postApiNotificationTrigger<TData = void>(gatewayContractsNotificationTriggerNotification: GatewayContractsNotificationTriggerNotification, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiNotificationTrigger<TData = void>(gatewayContractsNotificationTriggerNotification: GatewayContractsNotificationTriggerNotification, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiNotificationTrigger<TData = void>(gatewayContractsNotificationTriggerNotification: GatewayContractsNotificationTriggerNotification, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiNotificationTrigger<TData = void>(
    gatewayContractsNotificationTriggerNotification: GatewayContractsNotificationTriggerNotification, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/notification/trigger`,
      gatewayContractsNotificationTriggerNotification,options
    );
  }
 postApiNotificationUser<TData = void>(gatewayContractsNotificationUserIdRequest: GatewayContractsNotificationUserIdRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiNotificationUser<TData = void>(gatewayContractsNotificationUserIdRequest: GatewayContractsNotificationUserIdRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiNotificationUser<TData = void>(gatewayContractsNotificationUserIdRequest: GatewayContractsNotificationUserIdRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiNotificationUser<TData = void>(
    gatewayContractsNotificationUserIdRequest: GatewayContractsNotificationUserIdRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/notification/user`,
      gatewayContractsNotificationUserIdRequest,options
    );
  }
};

export type PostApiNotificationSendClientResult = NonNullable<void>
export type PostApiNotificationTemplateSendClientResult = NonNullable<void>
export type PostApiNotificationTriggerClientResult = NonNullable<void>
export type PostApiNotificationUserClientResult = NonNullable<void>
