/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type {
  GatewayContractsAssessmentAddQuestionRequest,
  GatewayContractsAssessmentCourseQuizStatusRequest,
  GatewayContractsAssessmentCreateQuiz,
  GatewayContractsAssessmentGetQuizForModuleRequest,
  GatewayContractsAssessmentGetUnquizzedRequest,
  GatewayContractsAssessmentResultRequest,
  GatewayContractsAssessmentSubmitQuiz
} from '../models';

import { http } from '../http';




  export const getAssessmentGateway = () => {
const postApiAssessmentQuizModule = (
    gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest,
 ) => {
      return http<void>(
      {url: `/api/assessment/quiz/module`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAssessmentGetQuizForModuleRequest
    },
      );
    }
  const postApiAssessmentQuiz = (
    gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz,
 ) => {
      return http<void>(
      {url: `/api/assessment/quiz`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAssessmentCreateQuiz
    },
      );
    }
  const postApiAssessmentQuizQuestions = (
    gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest,
 ) => {
      return http<void>(
      {url: `/api/assessment/quiz/questions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAssessmentAddQuestionRequest
    },
      );
    }
  const postApiAssessmentQuizSubmit = (
    gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz,
 ) => {
      return http<void>(
      {url: `/api/assessment/quiz/submit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAssessmentSubmitQuiz
    },
      );
    }
  const postApiAssessmentQuizResult = (
    gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest,
 ) => {
      return http<void>(
      {url: `/api/assessment/quiz/result`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAssessmentResultRequest
    },
      );
    }
  const postApiAssessmentCourseQuizStatus = (
    gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest,
 ) => {
      return http<void>(
      {url: `/api/assessment/course/quiz-status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAssessmentCourseQuizStatusRequest
    },
      );
    }
  const postApiAssessmentCourseUnquizzedModules = (
    gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest,
 ) => {
      return http<void>(
      {url: `/api/assessment/course/unquizzed-modules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAssessmentGetUnquizzedRequest
    },
      );
    }
  return {postApiAssessmentQuizModule,postApiAssessmentQuiz,postApiAssessmentQuizQuestions,postApiAssessmentQuizSubmit,postApiAssessmentQuizResult,postApiAssessmentCourseQuizStatus,postApiAssessmentCourseUnquizzedModules}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PostApiAssessmentQuizModuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssessmentGateway>['postApiAssessmentQuizModule']>>>
export type PostApiAssessmentQuizResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssessmentGateway>['postApiAssessmentQuiz']>>>
export type PostApiAssessmentQuizQuestionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssessmentGateway>['postApiAssessmentQuizQuestions']>>>
export type PostApiAssessmentQuizSubmitResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssessmentGateway>['postApiAssessmentQuizSubmit']>>>
export type PostApiAssessmentQuizResultResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssessmentGateway>['postApiAssessmentQuizResult']>>>
export type PostApiAssessmentCourseQuizStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssessmentGateway>['postApiAssessmentCourseQuizStatus']>>>
export type PostApiAssessmentCourseUnquizzedModulesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssessmentGateway>['postApiAssessmentCourseUnquizzedModules']>>>
