/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import { http } from '../http';




  export const getDebugAuth = () => {
const getApiDebugToken = (
    
 ) => {
      return http<void>(
      {url: `/api/debug/token`, method: 'GET'
    },
      );
    }
  return {getApiDebugToken}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetApiDebugTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDebugAuth>['getApiDebugToken']>>>
