/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type {
  GatewayContractsCourseContinueCourseRequest,
  GatewayContractsCourseCourse,
  GatewayContractsCourseCourseIdRequest,
  GatewayContractsCourseEnrollRequest,
  GatewayContractsCourseModuleIdRequest,
  GatewayContractsCourseUpdateCourseRequest
} from '../models';

import { http } from '../http';




  export const getGatewayCourse = () => {
const postApiCourseAll = (
    
 ) => {
      return http<void>(
      {url: `/api/course/all`, method: 'POST'
    },
      );
    }
  const postApiCourseById = (
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest,
 ) => {
      return http<void>(
      {url: `/api/course/by-id`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseCourseIdRequest
    },
      );
    }
  const postApiCourseCreate = (
    gatewayContractsCourseCourse: GatewayContractsCourseCourse,
 ) => {
      return http<void>(
      {url: `/api/course/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseCourse
    },
      );
    }
  const postApiCourseUpdate = (
    gatewayContractsCourseUpdateCourseRequest: GatewayContractsCourseUpdateCourseRequest,
 ) => {
      return http<void>(
      {url: `/api/course/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseUpdateCourseRequest
    },
      );
    }
  const postApiCourseDelete = (
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest,
 ) => {
      return http<void>(
      {url: `/api/course/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseCourseIdRequest
    },
      );
    }
  const postApiCourseInstructor = (
    
 ) => {
      return http<void>(
      {url: `/api/course/instructor`, method: 'POST'
    },
      );
    }
  const postApiCourseUnfinished = (
    
 ) => {
      return http<void>(
      {url: `/api/course/unfinished`, method: 'POST'
    },
      );
    }
  const postApiCourseContinue = (
    gatewayContractsCourseContinueCourseRequest: GatewayContractsCourseContinueCourseRequest,
 ) => {
      return http<void>(
      {url: `/api/course/continue`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseContinueCourseRequest
    },
      );
    }
  const postApiCourseEnroll = (
    gatewayContractsCourseEnrollRequest: GatewayContractsCourseEnrollRequest,
 ) => {
      return http<void>(
      {url: `/api/course/enroll`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseEnrollRequest
    },
      );
    }
  const postApiCourseEnrolled = (
    
 ) => {
      return http<void>(
      {url: `/api/course/enrolled`, method: 'POST'
    },
      );
    }
  const postApiCourseModules = (
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest,
 ) => {
      return http<void>(
      {url: `/api/course/modules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseCourseIdRequest
    },
      );
    }
  const postApiCourseModule = (
    gatewayContractsCourseModuleIdRequest: GatewayContractsCourseModuleIdRequest,
 ) => {
      return http<void>(
      {url: `/api/course/module`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseModuleIdRequest
    },
      );
    }
  const postApiCourseCategories = (
    
 ) => {
      return http<void>(
      {url: `/api/course/categories`, method: 'POST'
    },
      );
    }
  const postApiCoursePublish = (
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest,
 ) => {
      return http<void>(
      {url: `/api/course/publish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseCourseIdRequest
    },
      );
    }
  const postApiCourseRestore = (
    gatewayContractsCourseCourseIdRequest: GatewayContractsCourseCourseIdRequest,
 ) => {
      return http<void>(
      {url: `/api/course/restore`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsCourseCourseIdRequest
    },
      );
    }
  return {postApiCourseAll,postApiCourseById,postApiCourseCreate,postApiCourseUpdate,postApiCourseDelete,postApiCourseInstructor,postApiCourseUnfinished,postApiCourseContinue,postApiCourseEnroll,postApiCourseEnrolled,postApiCourseModules,postApiCourseModule,postApiCourseCategories,postApiCoursePublish,postApiCourseRestore}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PostApiCourseAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseAll']>>>
export type PostApiCourseByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseById']>>>
export type PostApiCourseCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseCreate']>>>
export type PostApiCourseUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseUpdate']>>>
export type PostApiCourseDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseDelete']>>>
export type PostApiCourseInstructorResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseInstructor']>>>
export type PostApiCourseUnfinishedResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseUnfinished']>>>
export type PostApiCourseContinueResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseContinue']>>>
export type PostApiCourseEnrollResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseEnroll']>>>
export type PostApiCourseEnrolledResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseEnrolled']>>>
export type PostApiCourseModulesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseModules']>>>
export type PostApiCourseModuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseModule']>>>
export type PostApiCourseCategoriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseCategories']>>>
export type PostApiCoursePublishResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCoursePublish']>>>
export type PostApiCourseRestoreResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayCourse>['postApiCourseRestore']>>>
