/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type {
  GatewayContractsAuthLoginRequest,
  GatewayContractsAuthRegisterRequest,
  GetApiGatewayAuthExternalResponseParams,
  GetApiGatewayAuthGoogleLoginParams,
  GetApiGatewayAuthLogoutParams,
  GetApiGatewayAuthMicrosoftLoginParams
} from '../models';

import { http } from '../http';




  export const getGatewayAuth = () => {
const getApiGatewayAuthGoogleLogin = (
    params?: GetApiGatewayAuthGoogleLoginParams,
 ) => {
      return http<void>(
      {url: `/api/GatewayAuth/google-login`, method: 'GET',
        params
    },
      );
    }
  const getApiGatewayAuthMicrosoftLogin = (
    params?: GetApiGatewayAuthMicrosoftLoginParams,
 ) => {
      return http<void>(
      {url: `/api/GatewayAuth/microsoft-login`, method: 'GET',
        params
    },
      );
    }
  const getApiGatewayAuthExternalResponse = (
    params?: GetApiGatewayAuthExternalResponseParams,
 ) => {
      return http<void>(
      {url: `/api/GatewayAuth/external-response`, method: 'GET',
        params
    },
      );
    }
  const postApiGatewayAuthRefresh = (
    
 ) => {
      return http<void>(
      {url: `/api/GatewayAuth/refresh`, method: 'POST'
    },
      );
    }
  const getApiGatewayAuthLogout = (
    params?: GetApiGatewayAuthLogoutParams,
 ) => {
      return http<void>(
      {url: `/api/GatewayAuth/logout`, method: 'GET',
        params
    },
      );
    }
  const getApiGatewayAuthMe = (
    
 ) => {
      return http<void>(
      {url: `/api/GatewayAuth/me`, method: 'GET'
    },
      );
    }
  const postApiGatewayAuthLocalRegister = (
    gatewayContractsAuthRegisterRequest: GatewayContractsAuthRegisterRequest,
 ) => {
      return http<void>(
      {url: `/api/GatewayAuth/local-register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAuthRegisterRequest
    },
      );
    }
  const postApiGatewayAuthLocalLogin = (
    gatewayContractsAuthLoginRequest: GatewayContractsAuthLoginRequest,
 ) => {
      return http<void>(
      {url: `/api/GatewayAuth/local-login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsAuthLoginRequest
    },
      );
    }
  return {getApiGatewayAuthGoogleLogin,getApiGatewayAuthMicrosoftLogin,getApiGatewayAuthExternalResponse,postApiGatewayAuthRefresh,getApiGatewayAuthLogout,getApiGatewayAuthMe,postApiGatewayAuthLocalRegister,postApiGatewayAuthLocalLogin}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetApiGatewayAuthGoogleLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayAuth>['getApiGatewayAuthGoogleLogin']>>>
export type GetApiGatewayAuthMicrosoftLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayAuth>['getApiGatewayAuthMicrosoftLogin']>>>
export type GetApiGatewayAuthExternalResponseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayAuth>['getApiGatewayAuthExternalResponse']>>>
export type PostApiGatewayAuthRefreshResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayAuth>['postApiGatewayAuthRefresh']>>>
export type GetApiGatewayAuthLogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayAuth>['getApiGatewayAuthLogout']>>>
export type GetApiGatewayAuthMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayAuth>['getApiGatewayAuthMe']>>>
export type PostApiGatewayAuthLocalRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayAuth>['postApiGatewayAuthLocalRegister']>>>
export type PostApiGatewayAuthLocalLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayAuth>['postApiGatewayAuthLocalLogin']>>>
