/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type {
  GatewayContractsUsersCompleteProfileRequest,
  GatewayContractsUsersUpdateUserRoleRequest,
  GatewayContractsUsersUserIdRequest
} from '../models';

import { http } from '../http';




  export const getGatewayUsers = () => {
const postApiUsersAll = (
    
 ) => {
      return http<void>(
      {url: `/api/users/all`, method: 'POST'
    },
      );
    }
  const postApiUsersById = (
    gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest,
 ) => {
      return http<void>(
      {url: `/api/users/by-id`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsUsersUserIdRequest
    },
      );
    }
  const postApiUsersDelete = (
    gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest,
 ) => {
      return http<void>(
      {url: `/api/users/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsUsersUserIdRequest
    },
      );
    }
  const postApiUsersCompleteProfile = (
    gatewayContractsUsersCompleteProfileRequest: GatewayContractsUsersCompleteProfileRequest,
 ) => {
      return http<void>(
      {url: `/api/users/complete-profile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsUsersCompleteProfileRequest
    },
      );
    }
  const postApiUsersRolesAll = (
    
 ) => {
      return http<void>(
      {url: `/api/users/roles/all`, method: 'POST'
    },
      );
    }
  const postApiUsersRolesUser = (
    gatewayContractsUsersUserIdRequest: GatewayContractsUsersUserIdRequest,
 ) => {
      return http<void>(
      {url: `/api/users/roles/user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsUsersUserIdRequest
    },
      );
    }
  const postApiUsersRolesUpdate = (
    gatewayContractsUsersUpdateUserRoleRequest: GatewayContractsUsersUpdateUserRoleRequest,
 ) => {
      return http<void>(
      {url: `/api/users/roles/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsUsersUpdateUserRoleRequest
    },
      );
    }
  return {postApiUsersAll,postApiUsersById,postApiUsersDelete,postApiUsersCompleteProfile,postApiUsersRolesAll,postApiUsersRolesUser,postApiUsersRolesUpdate}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PostApiUsersAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayUsers>['postApiUsersAll']>>>
export type PostApiUsersByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayUsers>['postApiUsersById']>>>
export type PostApiUsersDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayUsers>['postApiUsersDelete']>>>
export type PostApiUsersCompleteProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayUsers>['postApiUsersCompleteProfile']>>>
export type PostApiUsersRolesAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayUsers>['postApiUsersRolesAll']>>>
export type PostApiUsersRolesUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayUsers>['postApiUsersRolesUser']>>>
export type PostApiUsersRolesUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGatewayUsers>['postApiUsersRolesUpdate']>>>
