/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type {
  GatewayContractsNotificationEmailRequest,
  GatewayContractsNotificationTemplateRequest,
  GatewayContractsNotificationTriggerNotification,
  GatewayContractsNotificationUserIdRequest
} from '../models';

import { http } from '../http';




  export const getNotificationGateway = () => {
const postApiNotificationSend = (
    gatewayContractsNotificationEmailRequest: GatewayContractsNotificationEmailRequest,
 ) => {
      return http<void>(
      {url: `/api/notification/send`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsNotificationEmailRequest
    },
      );
    }
  const postApiNotificationTemplateSend = (
    gatewayContractsNotificationTemplateRequest: GatewayContractsNotificationTemplateRequest,
 ) => {
      return http<void>(
      {url: `/api/notification/template/send`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsNotificationTemplateRequest
    },
      );
    }
  const postApiNotificationTrigger = (
    gatewayContractsNotificationTriggerNotification: GatewayContractsNotificationTriggerNotification,
 ) => {
      return http<void>(
      {url: `/api/notification/trigger`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsNotificationTriggerNotification
    },
      );
    }
  const postApiNotificationUser = (
    gatewayContractsNotificationUserIdRequest: GatewayContractsNotificationUserIdRequest,
 ) => {
      return http<void>(
      {url: `/api/notification/user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsNotificationUserIdRequest
    },
      );
    }
  return {postApiNotificationSend,postApiNotificationTemplateSend,postApiNotificationTrigger,postApiNotificationUser}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PostApiNotificationSendResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotificationGateway>['postApiNotificationSend']>>>
export type PostApiNotificationTemplateSendResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotificationGateway>['postApiNotificationTemplateSend']>>>
export type PostApiNotificationTriggerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotificationGateway>['postApiNotificationTrigger']>>>
export type PostApiNotificationUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotificationGateway>['postApiNotificationUser']>>>
