/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type {
  GatewayContractsProgressModuleCompleteRequest,
  ProgressGatewayControllerProgressRecordDto
} from '../models';

import { http } from '../http';




  export const getProgressGateway = () => {
const postApiProgressUser = (
    
 ) => {
      return http<ProgressGatewayControllerProgressRecordDto[]>(
      {url: `/api/progress/user`, method: 'POST'
    },
      );
    }
  const postApiProgressCompleteModule = (
    gatewayContractsProgressModuleCompleteRequest: GatewayContractsProgressModuleCompleteRequest,
 ) => {
      return http<void>(
      {url: `/api/progress/complete-module`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gatewayContractsProgressModuleCompleteRequest
    },
      );
    }
  return {postApiProgressUser,postApiProgressCompleteModule}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PostApiProgressUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProgressGateway>['postApiProgressUser']>>>
export type PostApiProgressCompleteModuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProgressGateway>['postApiProgressCompleteModule']>>>
