/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  DTOs4AssessmentServiceAddQuestionResponseDto,
  DTOs4AssessmentServiceCourseQuizStatusResponseDto,
  DTOs4AssessmentServiceCreateQuizResponseDto,
  DTOs4AssessmentServiceQuizForModuleDto,
  DTOs4AssessmentServiceQuizResultDto,
  GatewayContractsAssessmentAddQuestionRequest,
  GatewayContractsAssessmentCourseQuizStatusRequest,
  GatewayContractsAssessmentCreateQuiz,
  GatewayContractsAssessmentGetQuizForModuleRequest,
  GatewayContractsAssessmentGetUnquizzedRequest,
  GatewayContractsAssessmentResultRequest,
  GatewayContractsAssessmentSubmitQuiz
} from '../models';




interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class AssessmentGatewayService {
  private readonly http = inject(HttpClient);
 postApiAssessmentQuizModule<TData = DTOs4AssessmentServiceQuizForModuleDto>(gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuizModule<TData = DTOs4AssessmentServiceQuizForModuleDto>(gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuizModule<TData = DTOs4AssessmentServiceQuizForModuleDto>(gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuizModule<TData = DTOs4AssessmentServiceQuizForModuleDto>(
    gatewayContractsAssessmentGetQuizForModuleRequest: GatewayContractsAssessmentGetQuizForModuleRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz/module`,
      gatewayContractsAssessmentGetQuizForModuleRequest,options
    );
  }
 postApiAssessmentQuiz<TData = DTOs4AssessmentServiceCreateQuizResponseDto>(gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuiz<TData = DTOs4AssessmentServiceCreateQuizResponseDto>(gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuiz<TData = DTOs4AssessmentServiceCreateQuizResponseDto>(gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuiz<TData = DTOs4AssessmentServiceCreateQuizResponseDto>(
    gatewayContractsAssessmentCreateQuiz: GatewayContractsAssessmentCreateQuiz, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz`,
      gatewayContractsAssessmentCreateQuiz,options
    );
  }
 postApiAssessmentQuizQuestions<TData = DTOs4AssessmentServiceAddQuestionResponseDto>(gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuizQuestions<TData = DTOs4AssessmentServiceAddQuestionResponseDto>(gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuizQuestions<TData = DTOs4AssessmentServiceAddQuestionResponseDto>(gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuizQuestions<TData = DTOs4AssessmentServiceAddQuestionResponseDto>(
    gatewayContractsAssessmentAddQuestionRequest: GatewayContractsAssessmentAddQuestionRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz/questions`,
      gatewayContractsAssessmentAddQuestionRequest,options
    );
  }
 postApiAssessmentQuizSubmit<TData = DTOs4AssessmentServiceQuizResultDto>(gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuizSubmit<TData = DTOs4AssessmentServiceQuizResultDto>(gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuizSubmit<TData = DTOs4AssessmentServiceQuizResultDto>(gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuizSubmit<TData = DTOs4AssessmentServiceQuizResultDto>(
    gatewayContractsAssessmentSubmitQuiz: GatewayContractsAssessmentSubmitQuiz, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz/submit`,
      gatewayContractsAssessmentSubmitQuiz,options
    );
  }
 postApiAssessmentQuizResult<TData = DTOs4AssessmentServiceQuizResultDto>(gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentQuizResult<TData = DTOs4AssessmentServiceQuizResultDto>(gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentQuizResult<TData = DTOs4AssessmentServiceQuizResultDto>(gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentQuizResult<TData = DTOs4AssessmentServiceQuizResultDto>(
    gatewayContractsAssessmentResultRequest: GatewayContractsAssessmentResultRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/quiz/result`,
      gatewayContractsAssessmentResultRequest,options
    );
  }
 postApiAssessmentCourseQuizStatus<TData = DTOs4AssessmentServiceCourseQuizStatusResponseDto>(gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentCourseQuizStatus<TData = DTOs4AssessmentServiceCourseQuizStatusResponseDto>(gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentCourseQuizStatus<TData = DTOs4AssessmentServiceCourseQuizStatusResponseDto>(gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentCourseQuizStatus<TData = DTOs4AssessmentServiceCourseQuizStatusResponseDto>(
    gatewayContractsAssessmentCourseQuizStatusRequest: GatewayContractsAssessmentCourseQuizStatusRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/course/quiz-status`,
      gatewayContractsAssessmentCourseQuizStatusRequest,options
    );
  }
 postApiAssessmentCourseUnquizzedModules<TData = number[]>(gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAssessmentCourseUnquizzedModules<TData = number[]>(gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAssessmentCourseUnquizzedModules<TData = number[]>(gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAssessmentCourseUnquizzedModules<TData = number[]>(
    gatewayContractsAssessmentGetUnquizzedRequest: GatewayContractsAssessmentGetUnquizzedRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/assessment/course/unquizzed-modules`,
      gatewayContractsAssessmentGetUnquizzedRequest,options
    );
  }
};

export type PostApiAssessmentQuizModuleClientResult = NonNullable<DTOs4AssessmentServiceQuizForModuleDto>
export type PostApiAssessmentQuizClientResult = NonNullable<DTOs4AssessmentServiceCreateQuizResponseDto>
export type PostApiAssessmentQuizQuestionsClientResult = NonNullable<DTOs4AssessmentServiceAddQuestionResponseDto>
export type PostApiAssessmentQuizSubmitClientResult = NonNullable<DTOs4AssessmentServiceQuizResultDto>
export type PostApiAssessmentQuizResultClientResult = NonNullable<DTOs4AssessmentServiceQuizResultDto>
export type PostApiAssessmentCourseQuizStatusClientResult = NonNullable<DTOs4AssessmentServiceCourseQuizStatusResponseDto>
export type PostApiAssessmentCourseUnquizzedModulesClientResult = NonNullable<number[]>
