/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GatewayContractsProgressModuleCompleteRequest,
  GatewayControllersProgressGatewayControllerProgressRecordDto
} from '../models';




interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class ProgressGatewayService {
  private readonly http = inject(HttpClient);
 postApiProgressUser<TData = GatewayControllersProgressGatewayControllerProgressRecordDto[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiProgressUser<TData = GatewayControllersProgressGatewayControllerProgressRecordDto[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiProgressUser<TData = GatewayControllersProgressGatewayControllerProgressRecordDto[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiProgressUser<TData = GatewayControllersProgressGatewayControllerProgressRecordDto[]>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/progress/user`,undefined,options
    );
  }
 postApiProgressCompleteModule<TData = void>(gatewayContractsProgressModuleCompleteRequest: GatewayContractsProgressModuleCompleteRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiProgressCompleteModule<TData = void>(gatewayContractsProgressModuleCompleteRequest: GatewayContractsProgressModuleCompleteRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiProgressCompleteModule<TData = void>(gatewayContractsProgressModuleCompleteRequest: GatewayContractsProgressModuleCompleteRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiProgressCompleteModule<TData = void>(
    gatewayContractsProgressModuleCompleteRequest: GatewayContractsProgressModuleCompleteRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/progress/complete-module`,
      gatewayContractsProgressModuleCompleteRequest,options
    );
  }
};

export type PostApiProgressUserClientResult = NonNullable<GatewayControllersProgressGatewayControllerProgressRecordDto[]>
export type PostApiProgressCompleteModuleClientResult = NonNullable<void>
