/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsAuthLoginRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}
