/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsNotificationNotificationType } from './gatewayContractsNotificationNotificationType';
import type { GatewayContractsNotificationTriggerNotificationData } from './gatewayContractsNotificationTriggerNotificationData';

export interface GatewayContractsNotificationTriggerNotification {
  userId: string;
  type?: GatewayContractsNotificationNotificationType;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  data?: GatewayContractsNotificationTriggerNotificationData;
}
