/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsCourseModule {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  content: string;
}
