/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface ProgressGatewayControllerProgressRecordDto {
  courseId?: number;
  /** @nullable */
  moduleId?: number | null;
  isCompleted?: boolean;
  progressPercent?: number;
}
