/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { DTOs4AssessmentServiceQuestionDetailDto } from './dTOs4AssessmentServiceQuestionDetailDto';

export interface DTOs4AssessmentServiceQuizForModuleDto {
  quizId?: number;
  moduleId?: number;
  /** @nullable */
  title?: string | null;
  timeLimitMinutes?: number;
  totalMarks?: number;
  alreadyPassed?: boolean;
  /** @nullable */
  questions?: DTOs4AssessmentServiceQuestionDetailDto[] | null;
}
