/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { DTOs4AssessmentServiceQuizModuleStatusDto } from './dTOs4AssessmentServiceQuizModuleStatusDto';

export interface DTOs4AssessmentServiceCourseQuizStatusResponseDto {
  courseId?: number;
  allQuizzesCreated?: boolean;
  /** @nullable */
  modules?: DTOs4AssessmentServiceQuizModuleStatusDto[] | null;
  /** @nullable */
  nextPendingModuleId?: number | null;
  /** @nullable */
  error?: string | null;
}
