/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface DTOs4AssessmentServiceAddQuestionResponseDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  questionId?: number | null;
}
