/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface DTOs3UserServiceUpdateUserRoleRequest {
  userId?: string;
  roleId?: number;
}
