/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsCourseUpdateCourse } from './gatewayContractsCourseUpdateCourse';

export interface GatewayContractsCourseUpdateCourseRequest {
  courseId?: number;
  course?: GatewayContractsCourseUpdateCourse;
}
