/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsAssessmentSubmitAnswer } from './gatewayContractsAssessmentSubmitAnswer';

export interface GatewayContractsAssessmentSubmitQuiz {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  quizId?: number;
  userId: string;
  /**
   * @minItems 1
   * @nullable
   */
  answers?: GatewayContractsAssessmentSubmitAnswer[] | null;
}
