/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export type GatewayContractsNotificationNotificationType = typeof GatewayContractsNotificationNotificationType[keyof typeof GatewayContractsNotificationNotificationType];


export const GatewayContractsNotificationNotificationType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
