/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsUsersCompleteProfileRequest {
  userId: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  role: string;
}
