/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsCourseCourse } from './gatewayContractsCourseCourse';

export interface GatewayContractsCourseCategory {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  courses?: GatewayContractsCourseCourse[] | null;
}
