/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsAssessmentCreateQuiz {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  moduleId?: number;
  /** @minLength 1 */
  title: string;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  timeLimitMinutes?: number;
}
