/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsCourseCategory } from './gatewayContractsCourseCategory';
import type { GatewayContractsCourseEnrollment } from './gatewayContractsCourseEnrollment';
import type { GatewayContractsCourseModule } from './gatewayContractsCourseModule';

export interface GatewayContractsCourseCourse {
  id?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  categoryId?: number;
  /** @nullable */
  instructorUserId?: string | null;
  isDeleted?: boolean;
  isDraft?: boolean;
  category?: GatewayContractsCourseCategory;
  /** @nullable */
  enrollments?: GatewayContractsCourseEnrollment[] | null;
  /** @nullable */
  modules?: GatewayContractsCourseModule[] | null;
}
