/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsCourseModuleCreate } from './gatewayContractsCourseModuleCreate';

export interface GatewayContractsCourseCourseCreateRequest {
  /** @minLength 1 */
  title: string;
  /** @nullable */
  description?: string | null;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  categoryId?: number;
  /** @minLength 1 */
  instructorUserId: string;
  /**
   * @minItems 1
   * @nullable
   */
  modules?: GatewayContractsCourseModuleCreate[] | null;
}
