<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>

		<!-- Correct Coverlet syntax -->
		<ExcludeByFile>**/DTOs/*.cs;**/Models/*.cs;**/Program.cs;**/Migrations/*.cs</ExcludeByFile>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="FluentAssertions" Version="8.8.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Gateway\Gateway.csproj" />
		<ProjectReference Include="..\Services\AssessmentService\AssessmentService.BLL\AssessmentService.BLL.csproj" />
		<ProjectReference Include="..\Services\AssessmentService\AssessmentService.DAL\AssessmentService.DAL.csproj" />
		<ProjectReference Include="..\Services\AssessmentService\AssessmentService.Web\AssessmentService.Web.csproj" />
		<ProjectReference Include="..\Services\CourseService\CourseService.BLL\CourseService.BLL.csproj" />
		<ProjectReference Include="..\Services\CourseService\CourseService.DAL\CourseService.DAL.csproj" />
		<ProjectReference Include="..\Services\CourseService\CourseService.Web\CourseService.Web.csproj" />
		<ProjectReference Include="..\Services\GatewayService\GatewayService.BLL\GatewayService.BLL.csproj" />
		<ProjectReference Include="..\Services\GatewayService\GatewayService.DAL\GatewayService.DAL.csproj" />
		<ProjectReference Include="..\Services\GatewayService\GatewayService.Web\GatewayService.Web.csproj" />
		<ProjectReference Include="..\Services\NotificationService\NotificationService.BLL\NotificationService.BLL.csproj" />
		<ProjectReference Include="..\Services\NotificationService\NotificationService.DAL\NotificationService.DAL.csproj" />
		<ProjectReference Include="..\Services\NotificationService\NotificationService.Web\NotificationService.Web.csproj" />
		<ProjectReference Include="..\Services\ProgresService\ProgresService.BLL\ProgresService.BLL.csproj" />
		<ProjectReference Include="..\Services\ProgresService\ProgresService.DAL\ProgresService.DAL.csproj" />
		<ProjectReference Include="..\Services\ProgresService\ProgresService.Web\ProgresService.Web.csproj" />
		<ProjectReference Include="..\Services\UserService\UserService.BLL\UserService.BLL.csproj" />
		<ProjectReference Include="..\Services\UserService\UserService.DAL\UserService.DAL.csproj" />
		<ProjectReference Include="..\Services\UserService\UserService.Web\UserService.Web.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
