/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface DTOs2CourseServiceModuleContentResponseDto {
  id?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  quizId?: number;
}
