/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { DTOs2CourseServiceModuleSummaryDto } from './dTOs2CourseServiceModuleSummaryDto';

export interface DTOs2CourseServiceCourseResponseDto {
  id?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  categoryId?: number;
  instructorId?: string;
  /** @nullable */
  instructorName?: string | null;
  modules: DTOs2CourseServiceModuleSummaryDto[];
  isDraft?: boolean;
  isDeleted?: boolean;
}
