/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface DTOs2CourseServiceEnrolledCourseResponseDto {
  id: number;
  /** @minLength 1 */
  title: string;
}
