/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface DTOs4AssessmentServiceAnswerOptionDto {
  id?: number;
  /** @nullable */
  text?: string | null;
}
