/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { DTOs4AssessmentServiceAnswerOptionDto } from './dTOs4AssessmentServiceAnswerOptionDto';

export interface DTOs4AssessmentServiceQuestionDetailDto {
  id?: number;
  /** @nullable */
  text?: string | null;
  marks?: number;
  /** @nullable */
  answers?: DTOs4AssessmentServiceAnswerOptionDto[] | null;
}
