/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface DTOs2CourseServiceCategoryResponseDto {
  id?: number;
  /** @nullable */
  name?: string | null;
}
