/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface DTOs4AssessmentServiceQuizResultDto {
  totalQuestions?: number;
  correctAnswers?: number;
  totalMarks?: number;
  obtainedMarks?: number;
  percentage?: number;
  passed?: boolean;
  alreadyPassed?: boolean;
  /** @nullable */
  statusMessage?: string | null;
  submissionId?: string;
}
