/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface DTOs4AssessmentServiceCreateQuizResponseDto {
  alreadyExists?: boolean;
  quizId?: number;
  /** @nullable */
  title?: string | null;
  moduleId?: number;
  /** @nullable */
  message?: string | null;
}
