/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsCourseCourse } from './gatewayContractsCourseCourse';

export interface GatewayContractsCourseEnrollment {
  id?: number;
  courseId?: number;
  /** @nullable */
  userId?: string | null;
  enrolledAt?: string;
  course?: GatewayContractsCourseCourse;
}
