/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsNotificationEmailRequest {
  userId: string;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  body?: string | null;
}
