/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsCourseCourse } from './gatewayContractsCourseCourse';

export interface GatewayContractsCourseModule {
  id?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  courseId?: number;
  course?: GatewayContractsCourseCourse;
}
