/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsUsersCompleteProfileRequest {
  userId: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  role: string;
}
