/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsCourseUpdateModule } from './gatewayContractsCourseUpdateModule';

export interface GatewayContractsCourseUpdateCourse {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  categoryId?: number;
  /** @nullable */
  modules?: GatewayContractsCourseUpdateModule[] | null;
}
