/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsAssessmentCreateQuestion {
  /** @minLength 1 */
  question: string;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  marks?: number;
  /**
   * @minItems 4
   * @maxItems 4
   * @nullable
   */
  options?: string[] | null;
  /**
   * @minimum 0
   * @maximum 3
   */
  correctAnswerIndex?: number;
}
