/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsAssessmentCreateQuestion } from './gatewayContractsAssessmentCreateQuestion';

export interface GatewayContractsAssessmentAddQuestionRequest {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  quizId?: number;
  question: GatewayContractsAssessmentCreateQuestion;
}
