/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsUsersUpdateUserRoleRequest {
  userId: string;
  /**
   * @minimum 1
   * @maximum 3
   */
  roleId?: number;
}
