/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsCourseEnrollRequest {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  courseId?: number;
}
