/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export type GatewayContractsNotificationNotificationType = typeof GatewayContractsNotificationNotificationType[keyof typeof GatewayContractsNotificationNotificationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GatewayContractsNotificationNotificationType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
