/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { GatewayContractsNotificationTemplateRequestModel } from './gatewayContractsNotificationTemplateRequestModel';

export interface GatewayContractsNotificationTemplateRequest {
  userId: string;
  /** @nullable */
  templateName?: string | null;
  /** @nullable */
  model?: GatewayContractsNotificationTemplateRequestModel;
}
