/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsUsersRoleresponse {
  id?: number;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  name?: string | null;
  /**
   * @minLength 0
   * @maxLength 255
   * @nullable
   */
  description?: string | null;
}
