/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface GatewayContractsCourseUpdateModule {
  id?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
}
